[build]
builder = "nixpacks"

[build.nixpacks]
pkgs = ["cmake", "gcc", "libffi", "openssl"]

[deploy]
startCommand = "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
